[workspace]
members = [
    "cache/in-memory",
    "command-parser",
    "embed-builder",
    "gateway",
    "gateway/examples/cluster",
    "gateway/examples/intents",
    "gateway/examples/metrics",
    "gateway/examples/request-members",
    "gateway/examples/shard",
    "gateway/queue",
    "http",
    "http/examples/allowed-mentions",
    "http/examples/get-message",
    "http/examples/proxy",
    "http/examples/slash-commands",
    "lavalink",
    "lavalink/examples/basic-lavalink-bot",
    "mention",
    "model",
    #"slash",
    "standby",
    "twilight",
    "util",
]
